Universal/Universal/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Universal.Models;
using PagedList;
using PagedList.Mvc;

namespace Universal.Controllers
{
    public class BlogController : Controller
    {
        dbQLUniversalDataContext data = new dbQLUniversalDataContext();

        // Lấy bài viết
        private List<BaiViet> LayBaiViet()
        {
            return data.BaiViets.ToList();
        }

        // Trang danh sách
        public ActionResult Index(int? page, string id = "0")
        {
            int pageSize = 2;
            int pageNum = (page ?? 1);
            if (id != "0" && id.Substring(0, 2) == "TL")
            {
                var BVietTL = from bv in data.BaiViets where bv.MaLoai == id select bv;
                return View(BVietTL.ToPagedList(pageNum, pageSize));
            }
            if (id != "0")
            {
                var BVietTK = from bv in data.BaiViets where bv.TaiKhoan == id select bv;
                return View(BVietTK.ToPagedList(pageNum, pageSize));
            }
            var BViet = LayBaiViet();
            return View(BViet.ToPagedList(pageNum, pageSize));
        }

        // Danh sách chủ đề
        public ActionResult ChuDe()
        {
            var chude = from cd in data.TheLoais select cd;
            return PartialView(chude);
        }

        // Danh sách thẻ
        public ActionResult The()
        {
            var the = from t in data.Thes select t;
            return PartialView(the.Skip(7));
        }

        // Nhận xét
        public ActionResult NhanXet(string id)
        {
            var nhanxet = from nx in data.NhanXets where nx.MaBV == id select nx;
            return PartialView(nhanxet);
        }

        // Trang chi tiết
        public ActionResult Detail(string id)
        {
            var BViet = from bv in data.BaiViets where bv.MaBV == id select bv;
            return View(BViet.Single());
        }
    }
}

Universal/Universal/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Universal.Models;

namespace Universal.Controllers
{
    public class HomeController : Controller
    {
        dbQLUniversalDataContext data = new dbQLUniversalDataContext();

        // Lấy n sản phẩm
        private List<SanPham> LaySanPham(int count)
        {
            return data.SanPhams.OrderByDescending(x => x.NgayDang).Take(count).ToList();
        }

        // Lấy n bài viết
        private List<BaiViet> LayBaiViet(int count)
        {
            return data.BaiViets.OrderByDescending(x => x.NgayDang).Take(count).ToList();
        }

        // Lấy 3 sản phẩm
        public ActionResult SPham()
        {
            var SPham = LaySanPham(6);
            return PartialView(SPham);
        }

        // Lấy 4 bài viết
        public ActionResult BViet()
        {
            var BViet = LayBaiViet(4);
            return PartialView(BViet);
        }

        // Trang chủ
        public ActionResult Index()
        {
            return View();
        }

        // Trang liên hệ
        public ActionResult Contact()
        {
            return View();
        }

        // Trang giới thiệu
        public ActionResult About()
        {
            return View();
        }

        // Trang câu hỏi thường gặp
        public ActionResult Faq()
        {
            return View();
        }

        // Trang lỗi 404
        [HandleError]
        public ActionResult Error()
        {
            return View();
        }
    }
}

Universal/Universal/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Universal.Models;
using PagedList;
using PagedList.Mvc;

namespace Universal.Controllers
{
    public class ProductController : Controller
    {
        dbQLUniversalDataContext data = new dbQLUniversalDataContext();
        
        // Lấy sản phẩm
        private List<SanPham> LaySanPham()
        {
            return data.SanPhams.ToList();
        }

        // Lấy n sản phẩm
        private List<SanPham> LaySanPham(int count)
        {
            return data.SanPhams.OrderByDescending(x => x.NgayDang).Take(count).ToList();
        }

        // Lấy 4 sản phẩm
        public ActionResult SPham()
        {
            var SPham = LaySanPham(4);
            return PartialView(SPham);
        }

        // Trang danh sách
        public ActionResult Index(int? page, string id = "0")
        {
            int pageSize = 6;
            int pageNum = (page ?? 1);
            if (id != "0" && id.Substring(0, 2) == "TL")
            {
                var SPhamTL = from sp in data.SanPhams where sp.MaLoai == id select sp;
                return View(SPhamTL.ToPagedList(pageNum, pageSize));
            }
            if (id != "0" && id.Substring(0, 2) == "TH")
            {
                var SPhamTH = from sp in data.SanPhams where sp.MaTH == id select sp;
                return View(SPhamTH.ToPagedList(pageNum, pageSize));
            }
            var SPham = LaySanPham();
            return View(SPham.ToPagedList(pageNum, pageSize));
        }

        // Danh sách chủ đề
        public ActionResult ChuDe()
        {
            var chude = from cd in data.TheLoais select cd;
            return PartialView(chude);
        }

        // Danh sách thương hiệu
        public ActionResult ThuongHieu()
        {
            var thuonghieu = from th in data.ThuongHieus select th;
            return PartialView(thuonghieu);
        }

        // Danh sách thẻ
        public ActionResult The()
        {
            var the = from t in data.Thes select t;
            return PartialView(the.Take(7));
        }

        // Trang chi tiết
        public ActionResult Detail(string id)
        {
            var Spham = from sp in data.SanPhams where sp.MaSP == id select sp;
            return View(Spham.Single());
        }
    }
}

Universal/Universal/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Universal.Models;
using PagedList;
using PagedList.Mvc;

namespace Universal.Controllers
{
    public class UserController : Controller
    {
        dbQLUniversalDataContext data = new dbQLUniversalDataContext();

        // Lấy dánh sách hóa đơn
        private List<DonHang> LayHoaDon()
        {
            ThanhVien session = (ThanhVien) Session["taikhoan"];
            return data.DonHangs.Where(x => x.TaiKhoan == session.TaiKhoan).ToList();
        }

        // Trang danh sách hóa đơn
        public ActionResult Index(int? page)
        {
            int pageSize = 5;
            int pageNum = (page ?? 1);
            var HDon = LayHoaDon();
            return View(HDon.ToPagedList(pageNum, pageSize));
        }

        // Trang chi tiết
        public ActionResult Detail(string id)
        {
            var HDon = from dh in data.DonHangs where dh.SoDH == id select dh;
            return View(HDon.Single());
        }

        // Láy danh sách CTHD
        public ActionResult ChiTiet(string id)
        {
            var chitiet = from ct in data.CTHDs where ct.SoDH == id select ct;
            return PartialView(chitiet);
        }

        // Trang đăng nhập
        [HttpGet]
        public ActionResult Signin()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Signin(FormCollection collection)
        {
            var TenDN = collection["TenDN"];
            var MatKhau = collection["MatKhau"];
            if (String.IsNullOrEmpty(TenDN))
                ViewData["Loi1"] = "Tên đăng nhập không được trống";
            else if (String.IsNullOrEmpty(MatKhau))
                ViewData["Loi2"] = "Mật khẩu không được trống";
            else
            {
                ThanhVien tv = data.ThanhViens.SingleOrDefault(n => n.TaiKhoan == TenDN && n.MatKhau == MatKhau);
                if (tv != null)
                {
                    Session["taikhoan"] = tv;
                    return RedirectToAction("Index", "Home");
                }
                else
                    ViewData["Loi2"] = "Tên đăng nhập hoặc mật khẩu không đúng!";
            }
            return View();
        }

        // Đăng xuất
        public ActionResult LogOut()
        {
            Session.Clear();
            return RedirectToAction("Index", "Home");
        }

        // Trang đăng ký
        [HttpGet]
        public ActionResult Signup()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Signup(FormCollection collection, ThanhVien th)
        {
            var TenDN = collection["TenDN"];
            var MatKhau = collection["MatKhau"];
            var HoKH = collection["HoKH"];
            var TenKH = collection["TenKH"];
            var NgaySinh = collection["birthday"];
            var GioiTinh = collection["gender"];
            var SoDT = collection["SoDT"];
            var Email = collection["Email"];
            var DiaChi = collection["DiaChi"];
            if (String.IsNullOrEmpty(TenDN))
            {
                ViewData["Loi1"] = "Tên đăng nhập không được trống";
            }
            else if (String.IsNullOrEmpty(MatKhau))
            {
                ViewData["Loi2"] = "Mật khẩu không được trống";
            }
            else if (String.IsNullOrEmpty(HoKH))
            {
                ViewData["Loi3"] = "Họ đệm khách hàng không được trống";
            }
            else if (String.IsNullOrEmpty(TenKH))
            {
                ViewData["Loi4"] = "Tên khách hàng không được trống";
            }
            else if (String.IsNullOrEmpty(NgaySinh))
            {
                ViewData["Loi5"] = "Ngày sinh không được trống";
            }
            else
            {
                th.TaiKhoan = TenDN;
                th.MatKhau = MatKhau;
                th.HoDemTV = HoKH;
                th.TenTV = TenKH;
                th.NgaySinh = DateTime.Parse(NgaySinh);
                if (GioiTinh == "male")
                    th.GioiTinh = true;
                else
                    th.GioiTinh = false;
                th.SDT = SoDT;
                th.Email = Email;
                th.DiaChi = DiaChi;
                th.TrangThai = true;
                th.MaNhom = "TK001";
                data.ThanhViens.InsertOnSubmit(th);
                data.SubmitChanges();
                return RedirectToAction("SignIn");
            }
            return this.Signup();
        }

        // Tạo ds yêu thích
        public List<YeuThich> LayYeuThich()
        {
            List<YeuThich> lstYeuthich = Session["Yeuthich"] as List<YeuThich>;
            if (lstYeuthich == null)
            {
                lstYeuthich = new List<YeuThich>();
                Session["Yeuthich"] = lstYeuthich;
            }
            return lstYeuthich;
        }
        
        // Thêm sp vào yêu thích
        public ActionResult ThemYeuThich(string sMaSP, string strURL)
        {
            List<YeuThich> lstYeuthich = LayYeuThich();
            YeuThich SanPham = lstYeuthich.Find(n => n.sMaSP == sMaSP);
            if (SanPham == null)
            {
                SanPham = new YeuThich(sMaSP);
                lstYeuthich.Add(SanPham);
            }
            return Redirect(strURL);
        }

        // Trang yêu thích
        public ActionResult Wishlist()
        {
            List<YeuThich> lstYeuthich = LayYeuThich();
            if (lstYeuthich.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }
            return View(lstYeuthich);
        }

        // Trang cá nhân
        [HttpGet]
        public ActionResult Account()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Account(FormCollection collection, ThanhVien th)
        {
            // Đổi mật khẩu
            var MatKhauCu = collection["MatKhauCu"];
            var MatKhauMoi = collection["MatKhauMoi"];
            if (String.IsNullOrEmpty(MatKhauCu))
                ViewBag.Loi1 = "Nhập mật khẩu cũ để xác nhận";
            else if (String.IsNullOrEmpty(MatKhauMoi))
                ViewBag.Loi2 = "Nhập mật khẩu mới";
            else
            {
                if (th.MatKhau == MatKhauCu)
                {
                    th.MatKhau = MatKhauMoi;
                    data.SubmitChanges();
                }
                else
                    ViewBag.Loi1 = "Sai mật khẩu cũ";
            }
            
            // Đổi thông tin
            var HoKH = collection["HoKH"];
            var TenKH = collection["TenKH"];
            var NgaySinh = collection["birthday"];
            var GioiTinh = collection["gender"];
            var SoDT = collection["SoDT"];
            var Email = collection["Email"];
            var DiaChi = collection["DiaChi"];
            return this.Account();
        }
    }
}

Universal/Universal/Views/Home/BViet.cshtml
@model IEnumerable<Universal.Models.BaiViet>

@foreach (var i in Model)
{
    <div class="col-lg-3">
        <div class="home-blog-post">
            <div class="image">
                <img src=" @i.DDHinh" alt="" height="250" width="250" style="text-align: center; margin: 0 auto; display: block">
                <div class="overlay d-flex align-items-center justify-content-center"><a href="@Url.Action("Detail", "Blog", new { id = i.MaBV})" class="btn btn-template-outlined-white"><i class="fa fa-chain"> </i> Đọc thêm</a></div>
            </div>
            <div class="text">
                <h4><a href="@Url.Action("Detail", "Blog", new { id = i.MaBV})"> @i.TenBV</a></h4>
                <p class="author-category">Đăng bỏi <a href="@Url.Action("Index", "Blog", new { id = i.TaiKhoan })"> @i.TaiKhoan</a> trong mục <a href="@Url.Action("Index", "Blog", new { id = i.MaLoai })"> @i.MaLoai</a></p>
                <p class="intro"> @i.TomTat</p><a href="@Url.Action("Detail", "Blog", new { id = i.MaBV})" class="btn btn-template-outlined">Đọc tiếp</a>
            </div>
        </div>
    </div>
}

Universal/Universal/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Home - Contact";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section styles {
    <link rel = "stylesheet" href = "https://unpkg.com/leaflet@1.6.0/dist/leaflet.css" integrity = "sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ==" crossorigin = "" >
}

<div id="heading-breadcrumbs" class="brder-top-0 border-bottom-0">
    <div class="container">
        <div class="row d-flex align-items-center flex-wrap">
            <div class="col-md-7">
                <h1 class="h2">Liên hệ</h1>
            </div>
            <div class="col-md-5">
                <ul class="breadcrumb d-flex justify-content-end">
                    <li class="breadcrumb-item">@Html.ActionLink("Trang chủ", "Index", "Home")</li>
                    <li class="breadcrumb-item active">Liên hệ</li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div id="content">
    <div id="contact" class="container">
        <section class="bar">
            <div class="row">
                <div class="col-md-12">
                    <div class="heading">
                        <h2>Chúng tôi ở đây để giúp bạn</h2>
                    </div>
                    <p class="lead">Bạn có tò mò về điều gì đó không? Bạn có một số loại vấn đề với sản phẩm của chúng tôi? Như tôi đã vội vàng được mời giải quyết với tài sản dân sự hạn chế của tôi. Thực sự mùa xuân trong một mức độ. Người phán xử nhưng lại xây dựng thế giới tiệc tùng đồng tính. Tất nhiên là anh ấy nhớ mặc dù được yêu cầu. Cử nhân giải nén được nâng cao tại. Giới hạn trong marianne được khai báo là vùng phụ cận.</p>
                    <p class="text-sm">Xin vui lòng liên hệ với chúng tôi, trung tâm dịch vụ khách hàng của chúng tôi đang làm việc cho bạn 24/7.</p>
                </div>
            </div>
        </section>
        <section>
            <div class="row text-center">
                <div class="col-md-4">
                    <div class="box-simple">
                        <div class="icon-outlined"><i class="fa fa-map-marker"></i></div>
                        <h3 class="h4">Địa chỉ</h3>
                        <p>13/25 Trịnh Thị Dối<br>Xã Đông Thạnh<br>Huyện Hóc Môn, <strong>Việt Nam</strong></p>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="box-simple">
                        <div class="icon-outlined"><i class="fa fa-phone"></i></div>
                        <h3 class="h4">Trung tâm liên lạc</h3>
                        <p>Số này là miễn phí nếu gọi từ Việt Nam. Nếu ở ngoài nước,  bạn nên sử dụng hình thức liên lạc điện tử.</p>
                        <p><strong><a href="tel:0949010239">0949 010 239</a></strong></p>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="box-simple">
                        <div class="icon-outlined"><i class="fa fa-envelope"></i></div>
                        <h3 class="h4">Email</h3>
                        <p>Vui lòng viết email cho chúng tôi.</p>
                        <p><strong><a href="mailto:UniversalShop@gmail.com">UniversalShop@gmail.com</a></strong></p>
                    </div>
                </div>
            </div>
        </section>
        <section class="bar pt-0">
            <div class="row">
                <div class="col-md-12">
                    <div class="heading text-center">
                        <h2>Mẫu liên hệ</h2>
                    </div>
                </div>
                <div class="col-md-8 mx-auto">
                    <form>
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="firstname">Tên</label>
                                    <input id="firstname" type="text" class="form-control">
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="lastname">Họ</label>
                                    <input id="lastname" type="text" class="form-control">
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="email">Email</label>
                                    <input id="email" type="text" class="form-control">
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="subject">Tiêu đề</label>
                                    <input id="subject" type="text" class="form-control">
                                </div>
                            </div>
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <label for="message">Tin nhắn</label>
                                    <textarea id="message" class="form-control"></textarea>
                                </div>
                            </div>
                            <div class="col-sm-12 text-center">
                                <button type="submit" class="btn btn-template-outlined"><i class="fa fa-envelope-o"></i> Gửi tin nhắn</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </section>
    </div>
    <div id="map"></div>
</div>

@section scripts {
    <script src = "https://unpkg.com/leaflet@1.6.0/dist/leaflet.js" integrity = "sha512-gZwIG9x3wUXg2hdXF6+rVkLF/0Vi9U8D2Ntg4Ga5I5BZpVkVxlJWbSQtXPSiUTtC0TjtGOmxa1AJPuV0CPthew==" crossorigin = "" ></script>
    <script src="~/Scripts/map.js"></script>
}

Universal/Universal/Views/Home/Faq.cshtml
@{
    ViewBag.Title = "Home - Faq";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="heading-breadcrumbs">
    <div class="container">
        <div class="row d-flex align-items-center flex-wrap">
            <div class="col-md-7">
                <h1 class="h2">Các câu hỏi thường gặp</h1>
            </div>
            <div class="col-md-5">
                <ul class="breadcrumb d-flex justify-content-end">
                    <li class="breadcrumb-item">@Html.ActionLink("Trang chủ", "Index", "Home")</li>
                    <li class="breadcrumb-item active">Các câu hỏi thường gặp</li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div id="content">
    <div class="container">
        <div class="row bar">
            <div class="col-md-12">
                <section>
                    <p class="lead">Nếu bạn có thắc mắc về chúng tôi thì có thể xem qua các câu hỏi thường gặp dưới đây</p>
                    <div id="accordion" role="tablist">
                        <div class="card card-primary">
                            <div id="headingOne" role="tab" class="card-header">
                                <h5 class="mb-0 mt-0"><a data-toggle="collapse" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">1. Tại Sao Tài Khoản Của Tôi Bị Khóa / Bị Giới Hạn?</a></h5>
                            </div>
                            <div id="collapseOne" role="tabpanel" aria-labelledby="headingOne" data-parent="#accordion" class="collapse show">
                                <div class="card-body">
                                    <p>Để đảm bảo tính bảo mật và an toàn cho Người dùng, Universal sẽ khóa / giới hạn tài khoản của bạn trong một số trường hợp:</p>
                                    <ul>
                                        <li>Vi phạm Điều khoản Dịch vụ của Universal.</li>
                                        <li>Tạo đơn hàng ảo, đánh giá ảo.</li>
                                        <li>Lạm dụng mã giảm giá, các chương trình trợ giá hoặc khuyến mãi tại Universal.</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="card card-primary">
                            <div id="headingTwo" role="tab" class="card-header">
                                <h5 class="mb-0 mt-0"><a data-toggle="collapse" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo" class="collapsed">2. Cách Đăng Nhập Tài Khoản Universal Khi Quên / Mất Mật Khẩu</a></h5>
                            </div>
                            <div id="collapseTwo" role="tabpanel" aria-labelledby="headingTwo" data-parent="#accordion" class="collapse">
                                <div class="card-body">Truy cập vào @Html.ActionLink("đây", "Account", "User") để lấy lại mật khẩu</div>
                            </div>
                        </div>
                        <div class="card card-primary">
                            <div id="headingThree" role="tab" class="card-header">
                                <h5 class="mb-0 mt-0"><a data-toggle="collapse" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree" class="collapsed"> 3. Sao Shipper Chưa Giao Hàng / Khi Nào Giao Hàng Cho Tôi / Tôi Muốn Hối Giao Hàng?</a></h5>
                            </div>
                            <div id="collapseThree" role="tabpanel" aria-labelledby="headingThree" data-parent="#accordion" class="collapse">
                                <div class="card-body">Nếu Shipper chưa giao hàng  / lấy hàng / hoàn trả đơn hàng theo đúng thời gian dự kiến, hãy liên hệ trực tiếp đơn vị vận chuyển theo thông tin <a href="tel:18006328">1800 6328</a> hoặc <a href="mailto:cskh@ghn.vn">cskh@ghn.vn</a></div>
                            </div>
                        </div>
                        <div class="card card-primary">
                            <div id="headingFour" role="tab" class="card-header">
                                <h5 class="mb-0 mt-0"><a data-toggle="collapse" href="#collapseFour" aria-expanded="false" aria-controls="collapseFive" class="collapsed">4. Tôi Muốn Kiểm Tra Đơn Hàng Giao Tới Đâu</a></h5>
                            </div>
                            <div id="collapseFour" role="tabpanel" aria-labelledby="headingFour" data-parent="#accordion" class="collapse">
                                <div class="card-body">
                                    <p>Nếu bạn chưa đăng nhập thì hãy đăng nhập sau đó xem tại @Html.ActionLink("đây", "Index", "User")</p>
                                </div>
                            </div>
                        </div>
                        <div class="card card-primary">
                            <div id="headingFive" role="tab" class="card-header">
                                <h5 class="mb-0 mt-0"><a data-toggle="collapse" href="#collapseFive" aria-expanded="false" aria-controls="collapseThree" class="collapsed"> 5. Tôi Không Thể Đặt Hàng / Đăng Ký Tài Khoản / Đăng Nhập Do Số Tài Khoản Đã Tồn Tại</a></h5>
                            </div>
                            <div id="collapseFive" role="tabpanel" aria-labelledby="headingFive" data-parent="#accordion" class="collapse">
                                <div class="card-body">
                                    <p>Theo quy định của Universal, một tên tài khoản chỉ có thể tạo duy nhất một tài khoản Universal..</p>
                                    <ul>
                                        <li>Tài khoản cũ là của bạn:            Truy cập @Html.ActionLink("đây", "Account", "User") để lấy lại mật khẩu</li>
                                        <li>Tài khoản cũ không phải của bạn:    Vui lòng dùng tên tài khoản khác để @Html.ActionLink("đăng ký", "Signup", "User")</li>
                                        <li>Tài khoản cũ đã bị khóa:            Chúng tôi không giải quyết trường hợp tài khoản đã bị khóa! Vui lòng @Html.ActionLink("đăng ký", "Signup", "User") bằng tên tài khoản khác tại</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <p class="text-muted">Nếu bạn vẫn chưa giải quyết được khúc mắc của mình, hãy @Html.ActionLink("Liên hệ với chúng tôi", "Contact", "Home"). Rất sẵn lòng khi được giúp các bạn!</p>
                </section>
            </div>
        </div>
    </div>
</div>

Universal/Universal/Views/Home/SPham.cshtml
@model IEnumerable<Universal.Models.SanPham>

@foreach (var i in Model)
{
    <div class="col-md-4">
        <div class="box-image">
            <div class="image">
                <img src=" @i.DDHinh" alt="" height="350" width="300" style="text-align: center; margin: 0 auto; display: block">
                <div class="overlay d-flex align-items-center justify-content-center">
                    <div class="content">
                        <div class="name">
                            <h3><a href="@Url.Action("Detail", "Product", new { id = i.MaSP })" class="color-white"> @i.TenSP</a></h3>
                        </div>
                        <div class="text">
                            <p class="buttons">
                                <a href="@Url.Action("Detail", "Product", new { id = i.MaSP })" class="btn btn-template-outlined-white">Xem chi tiết</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}